const test = require('node:test');
const assert = require('node:assert/strict');
const { readFileSync } = require('node:fs');
const { join } = require('node:path');

// M5 of design-docs/plans/2026-09-12-openapi-nguon-chung.md.
//
// This node is the third surface that describes the MADIAD Hub API, after the website docs and the
// agent pack. The first two drifted from the gateway and nobody found out until an outside tester
// did: `pinterest_board_id`, `subreddit` and `reddit_title` appeared 6/4/8 times in the docs and
// ZERO times in the pack, while the gateway threw a hard 400 without them. This file is what stops
// the node from being the next one.
//
// The comparison runs against dist/ — the code that actually ships — and against api/openapi.yaml,
// which is generated from the gateway source. So this is node-as-built versus gateway-as-described,
// not source versus source.
//
// WHY THIS IS NOT A camelCase→snake_case GUESS. The node is declarative: every field it sends
// declares its own wire name in `routing.request.body` / `.qs` / `.headers`. So the wire names are
// READ, not derived. That matters, because a hand-rolled `camelCase → snake_case` rule is exactly
// the kind of translation layer where a mismatch produces "no match found" and a subset check then
// passes: `videoUrl` → `video_url` works, but nothing would have told us if it did not.

const { MadiadHub } = require('../dist/nodes/MadiadHub/MadiadHub.node.js');
const d = new MadiadHub().description;

const SPEC_PATH = join(__dirname, '..', '..', 'api', 'openapi.yaml');
const SPEC = readFileSync(SPEC_PATH, 'utf8');

// `requestDefaults.baseURL` ends in /v1, and operation URLs are relative to it. The spec keys its
// paths with the /v1 prefix included, so the prefix has to be put back before anything is compared.
const BASE_PREFIX = new URL(d.requestDefaults.baseURL).pathname.replace(/\/$/, '');

// ── what the node actually sends ────────────────────────────────────────────────────────

/** operation value -> { method, url } taken from the operation's own routing. */
function nodeOperations() {
	const out = new Map();
	for (const p of d.properties.filter((x) => x.name === 'operation')) {
		for (const o of p.options ?? []) {
			const r = o.routing?.request;
			if (!r?.url) continue;
			out.set(o.value, { method: (r.method ?? 'GET').toUpperCase(), url: BASE_PREFIX + r.url });
		}
	}
	return out;
}

/**
 * Every field the node puts on the wire: { operation, place, name }.
 *
 * Walks the real property objects rather than the source text, and descends into `collection`
 * properties (the Options collections), whose members inherit the collection's operation.
 */
function nodeWireFields() {
	const rows = [];
	const visit = (p, inherited) => {
		const ops = p.displayOptions?.show?.operation ?? inherited;
		const r = p.routing?.request;
		if (r) {
			for (const place of ['body', 'qs', 'headers']) {
				for (const name of Object.keys(r[place] ?? {})) {
					for (const op of ops ?? []) rows.push({ op, place, name });
				}
			}
		}
		if (p.type === 'collection') for (const o of p.options ?? []) visit(o, ops);
	};
	for (const p of d.properties) visit(p, undefined);
	return rows;
}

// ── what the spec documents ─────────────────────────────────────────────────────────────

/**
 * "METHOD /path" -> Set of every field name the spec declares for it (query/path parameters plus
 * request-body properties).
 *
 * A line reader, not a YAML library: this package ships with zero runtime dependencies and the
 * file is machine-generated by api/_build.py, so its shape is fixed. The positive control below
 * is what keeps that choice honest — a reader that silently stops matching returns empty sets, and
 * an empty set passes every subset check underneath it.
 */
function specFieldsByOperation() {
	const out = new Map();
	let path = null;
	let key = null;
	let inParams = false;
	let inProps = false;
	for (const line of SPEC.split('\n')) {
		let m;
		if ((m = line.match(/^ {2}"(\/v1[^"]*)":$/))) {
			path = m[1];
			key = null;
			inParams = inProps = false;
			continue;
		}
		if (/^ {2}\S/.test(line)) {
			path = key = null;
			inParams = inProps = false;
			continue;
		}
		if ((m = line.match(/^ {4}(get|post|put|patch|delete):$/))) {
			key = path ? `${m[1].toUpperCase()} ${path}` : null;
			if (key && !out.has(key)) out.set(key, new Set());
			inParams = inProps = false;
			continue;
		}
		if (!key) continue;
		if (/^ {6}parameters:$/.test(line)) {
			inParams = true;
			inProps = false;
			continue;
		}
		if (/^ {6}\w/.test(line)) inParams = false;
		if (/^ {14}properties:$/.test(line)) {
			inProps = true;
			continue;
		}
		if (/^ {14}\w/.test(line)) inProps = false;
		// `[\w-]`, not `\w`: a header name can carry a hyphen, and `Idempotency-Key` does. With
		// `\w+` this reader silently returned nothing for every header parameter in the spec, so
		// the comparison below reported the spec as missing a header it actually declares. Same
		// shape as the digit hole found in the gateway extractors the same day: a character class
		// that excludes a character real names use.
		if (inParams && (m = line.match(/^ {8}- name: "([\w-]+)"$/))) out.get(key).add(m[1]);
		if (inProps && (m = line.match(/^ {16}([a-z_][a-z0-9_]*):$/))) out.get(key).add(m[1]);
	}
	return out;
}

// ── the gaps that were real, and are now closed ─────────────────────────────────────────
//
// This list was NOT empty when it was written. It held two holes in the spec, both verified
// against gateway/src rather than assumed:
//
//   POST /v1/posts/video  body  pinterest_board_id — the gateway refuses a Pinterest post without
//     it on EVERY post kind (assertPlatformRequirements, posts.ts:1290, checks only
//     `platforms.includes("pinterest")`, and handleVideo calls it at posts.ts:1462), while the spec
//     listed `pinterest` among the channels that endpoint accepts and omitted the one field that
//     makes such a post possible.
//   *  headers  Idempotency-Key — the spec declared NO header parameters at all (0 occurrences of
//     `in: "header"`, against 51 of `in: "query"`), so a generated client could not learn the header
//     exists, while `idempotency_conflict` / `idempotency_in_progress` are codes it can receive.
//
// Both were fixed in the spec on 2026-09-13, and the last test in this file is what forced this
// list to be emptied: an exemption that outlives the thing it excuses is how a fixed bug gets
// re-introduced without anyone noticing. Keep the list — not the entries — and keep that test.
const KNOWN_SPEC_GAPS = [];

const gapKey = (op, place, name) => `${op}|${place}|${name}`;
const GAP_SET = new Set(KNOWN_SPEC_GAPS.map((g) => gapKey(g.op, g.place, g.name)));
const isKnownGap = (op, place, name) =>
	GAP_SET.has(gapKey(op, place, name)) || GAP_SET.has(gapKey('*', place, name));

// ── positive controls, before any comparison ────────────────────────────────────────────
//
// Every assertion below this point is a subset check, and a subset check against an empty set
// passes. Measured 2026-09-12 in this very repo: the endpoint extractor returned 53 while the
// gateway served 75, and nothing anywhere went red. See feedback_coding_discipline §77.

test('the node scan still reads the built node (positive control)', () => {
	const ops = nodeOperations();
	assert.ok(ops.size >= 8, `only ${ops.size} operations read out of dist/ — the walker is broken`);
	for (const op of ['publishText', 'publishPhoto', 'publishVideo', 'getStatus', 'retry', 'unpublish']) {
		assert.ok(ops.has(op), `operation "${op}" disappeared from the scan`);
	}
	assert.equal(ops.get('publishVideo').url, '/v1/posts/video');
	assert.equal(ops.get('getStatus').method, 'GET');

	const rows = nodeWireFields();
	assert.ok(rows.length >= 30, `only ${rows.length} routed fields read — the routing walk is broken`);
	// One landmark per place, so a regression that loses ONE place is caught too.
	const has = (place, name) => rows.some((r) => r.place === place && r.name === name);
	assert.ok(has('body', 'video_url'), 'lost the body fields');
	assert.ok(has('qs', 'request_id'), 'lost the query-string fields');
	assert.ok(has('headers', 'Idempotency-Key'), 'lost the header fields');
	// And one that proves the collection descent works: this field only exists inside Options.
	assert.ok(has('body', 'pinterest_board_id'), 'lost the fields inside the Options collections');
});

test('the spec reader still reads the spec (positive control)', () => {
	assert.ok(SPEC.length > 20_000, `api/openapi.yaml is empty or truncated (${SPEC.length} bytes)`);
	const byOp = specFieldsByOperation();
	assert.ok(byOp.size >= 70, `only ${byOp.size} operations read out of the spec — the reader is broken`);
	// A landmark whose field set must be non-empty: an empty one would pass everything below.
	const text = byOp.get('POST /v1/posts/text');
	assert.ok(text, 'POST /v1/posts/text is missing from the spec');
	for (const f of ['profile_id', 'platforms', 'caption', 'subreddit']) {
		assert.ok(text.has(f), `the reader lost "${f}" from POST /v1/posts/text`);
	}
	assert.ok(byOp.get('GET /v1/posts/status')?.has('request_id'), 'query parameters are not being read');
});

test('the node URL scan agrees with a second, dumber measurement', () => {
	// Independent of the object walk: a flat grep for routed URLs over the shipped JS. If the two
	// disagree, one of them has stopped seeing something, and neither can be trusted on its own.
	// This is the counting check §77 asks for — the other side comes from somewhere the object
	// walk cannot reach.
	const src = readFileSync(join(__dirname, '..', 'dist', 'nodes', 'MadiadHub', 'PostDescription.js'), 'utf8');
	const grepped = new Set([...src.matchAll(/url:\s*'(\/[a-z/-]+)'/g)].map((m) => m[1]));
	const walked = new Set(
		[...nodeOperations().values()]
			.filter((o) => o.url.startsWith('/v1/posts'))
			.map((o) => o.url.slice(BASE_PREFIX.length)),
	);
	assert.ok(grepped.size >= 6, `the flat grep found only ${grepped.size} URLs — it is broken`);
	assert.deepEqual(
		[...walked].sort(),
		[...grepped].sort(),
		'the object walk and the flat grep disagree about which post URLs the node calls',
	);
});

// ── the direction M5 exists for ─────────────────────────────────────────────────────────

test('every endpoint the node calls exists in the spec', () => {
	const byOp = specFieldsByOperation();
	const missing = [];
	for (const [op, { method, url }] of nodeOperations()) {
		if (!byOp.has(`${method} ${url}`)) missing.push(`${op} -> ${method} ${url}`);
	}
	assert.deepEqual(
		missing.sort(),
		[],
		`the node calls endpoints the spec does not document, so a caller who believes the ` +
			`document would not find them: ${missing.join(', ')}`,
	);
});

test('every field the node sends is documented in the spec', () => {
	const byOp = specFieldsByOperation();
	const ops = nodeOperations();
	const undocumented = [];
	for (const { op, place, name } of nodeWireFields()) {
		if (place === 'headers') continue; // covered by its own test below
		const route = ops.get(op);
		assert.ok(route, `field "${name}" is attached to unknown operation "${op}"`);
		const documented = byOp.get(`${route.method} ${route.url}`);
		assert.ok(documented, `${route.method} ${route.url} is not in the spec at all`);
		if (documented.has(name)) continue;
		if (isKnownGap(`${route.method} ${route.url}`, place, name)) continue;
		undocumented.push(`${route.method} ${route.url}  ${place}.${name}  (node field for "${op}")`);
	}
	assert.deepEqual(
		[...new Set(undocumented)].sort(),
		[],
		`the node sends these and the spec never declares them. Either the node sends something ` +
			`the API does not take, or the spec is incomplete — check gateway/src before deciding ` +
			`which, then fix the losing side (or add a KNOWN_SPEC_GAPS entry with the evidence):\n  ` +
			`${[...new Set(undocumented)].join('\n  ')}`,
	);
});

test('every header the node sends is declared on that operation in the spec', () => {
	// This test used to compare headers against a hardcoded allowlist, because the spec declared no
	// header parameters AT ALL — 0 occurrences of `in: "header"` against 51 of `in: "query"`. That
	// hole was closed on 2026-09-13, so headers are now compared the same way body and query fields
	// are: against the spec, per operation. An allowlist that outlives its reason is how the next new
	// header slips in unnoticed.
	const byOp = specFieldsByOperation();
	const ops = nodeOperations();
	const sent = nodeWireFields().filter((r) => r.place === 'headers');

	// Two positive controls: an empty scan on either side passes every comparison below, and both
	// sides are read by regex out of files neither of them owns.
	assert.ok(sent.length > 0, 'no header reads out of the built node — the node scan is broken');
	assert.ok(
		sent.some((r) => r.name === 'Idempotency-Key'),
		'the node stopped sending Idempotency-Key, or the scan stopped seeing it',
	);

	const missing = [];
	for (const { op, name } of sent) {
		const route = ops.get(op);
		assert.ok(route, `header "${name}" is attached to unknown operation "${op}"`);
		const documented = byOp.get(`${route.method} ${route.url}`);
		assert.ok(documented, `${route.method} ${route.url} is not in the spec at all`);
		if (!documented.has(name)) missing.push(`${route.method} ${route.url}  ${name}`);
	}
	assert.deepEqual(
		[...new Set(missing)].sort(),
		[],
		'the node sends these headers and the spec does not declare them on that operation, so ' +
			'anything generated from the machine-readable part cannot know they exist',
	);
});

test('no entry in KNOWN_SPEC_GAPS has been fixed and left behind', () => {
	// The half that makes the allowlist a debt rather than a hole: the day the spec gains one of
	// these, this goes red and names the line to delete. Without it, an exemption outlives its
	// reason and then quietly excuses a real regression.
	const byOp = specFieldsByOperation();
	const stale = [];
	for (const g of KNOWN_SPEC_GAPS) {
		if (g.place === 'headers') {
			if (/in: "header"/.test(SPEC)) stale.push(`${g.name} — the spec now declares header parameters`);
			continue;
		}
		if (byOp.get(g.op)?.has(g.name)) stale.push(`${g.op} ${g.name} — the spec now documents it`);
	}
	assert.deepEqual(
		stale.sort(),
		[],
		`these KNOWN_SPEC_GAPS entries are no longer true. Delete them from ` +
			`test/spec-drift.test.js — an exemption that outlived its reason excuses the next real ` +
			`gap:\n  ${stale.join('\n  ')}`,
	);
});
